### ISSUE TITLE
threshold for d_eucl

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#12]
Oh my, I see that you've updated the code to calculate the cost using d_eucl, which is such a coincidence because I just finished that part too. However, I've encountered a problem, which is how to set the threshold. The configuration file only provides the threshold for giou3d, and I feel that may not be very appropriate. Do you have any suggestions? By the way, the image shows the d_eucl code I wrote, it's really quite the coincidence, huh.
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/0c8d9a31-922c-45b0-abee-12089ac5c5ae)
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/be8deaab-59cc-420f-b9c6-ebf34dac7412)

**Comment by lixiaoyu2000** [comment]
One of the simplest ways is to perform a linear search of parameters in a domain with a fixed step size based on the method AMOTA on the val set.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
