### ISSUE TITLE
How do I get .json file from the CenterPoint?

### ISSUE THREAD

**Issue by CrazyDreamYang** [lixiaoyu2000/Poly-MOT#16]
I refer to this link to get the json file.[https://gitee.com/open-mmlab/mmdetection3d/blob/master/docs/zh_cn/datasets/nuscenes_det.md#%E5%9F%BA%E4%BA%8E-lidar-%E7%9A%84%E6%96%B9%E6%B3%95](url).But it doesn,t work!

**Comment by lixiaoyu2000** [comment]
Please refer to this [issue](https://github.com/tianweiy/CenterPoint/issues/249).
