### ISSUE TITLE
velocity error

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#18]
I have a question regarding tracking results. In the results, the velocity of the same object in consecutive frames is completely opposite, but the tracking still seems to be correct. Why is this happening? Why does the situation where the velocity is completely opposite occur (this often happens when the velocity of an object in its first appearance is different from its second, third, and subsequent appearances)? And why is the tracking still accurate in such cases?

As shown in the images, the first image shows the first appearance of the pink box with the correct velocity direction. However, in the next two consecutive frames, the velocity direction appears to be incorrect

![prGjhWTdcT](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/8b122cab-39ec-4c1a-9b35-46465a1d93ea)

![p520L5CVQo](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/ea64ce4e-29bc-43de-9437-b822a8610a1a)
![whiPTi9lBV](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/8359edd3-9016-4b55-bda3-80ec650fa785)

**Comment by flora077** [comment]
In the image, the ego vehicle is represented as a solid shape

**Comment by lixiaoyu2000** [comment]
Since you didn't provide details on where the speed visualization (arrow) is drawn, I can't tell if the speed given is correct. However, there are a few insights you can consider:
- By default, the velocity is [initialized ](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L377) in the same direction as the object's yaw (forward motion). 
- The combined velocity in the Kalman Filter state is actually a physical vector, "+" means in the same direction as yaw, "-" means in the opposite direction of yaw. When checking the combined speed status, it is not only necessary to check the yaw of the obstacle, but also the positive and negative sign of the speed.
- In autonomous driving scenarios, examples of driving in the opposite direction are very rare. Therefore, when the combined velocity is found to be negative, this is usually due to a given error in yaw. It should also be noted that negative speed still correctly describes the movement of objects in the physical world (positive speed and real yaw, negative speed and yaw with a difference of 180 degrees, both express the same physical movement.).
- The simplest way to deal with the above situation is to make the negative speed positive and increase the yaw by 180 degrees.

**Comment by flora077** [comment]
Please do not close this issue. I will provide you with more detailed information on Monday and will continue to communicate with you after making improvements according to your suggestions. Thank you very much

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/05/2024 21:51 |
| To | lixiaoyu2000/Poly-MOT ***@***.***> |
| Cc | flora077 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [lixiaoyu2000/Poly-MOT] velocity error (Issue #18) |

Since you didn't provide details on where the speed visualization (arrow) is drawn, I can't tell if the speed given is correct. However, there are two insights you can consider:

By default, the velocity is initialized in the same direction as the object's yaw (forward motion).
The combined velocity in the Kalman Filter state is actually a physical vector, "+" means in the same direction as yaw, "-" means in the opposite direction of yaw. When checking the combined speed status, it is not only necessary to check the yaw of the obstacle, but also the positive and negative sign of the speed.
In autonomous driving scenarios, examples of driving in the opposite direction are very rare. Therefore, when the combined velocity is found to be negative, this is usually due to a given error in yaw. It should also be noted that negative speed still correctly describes the movement of objects in the physical world (positive speed and real yaw, negative speed and yaw with a difference of 180 degrees, both express the same physical movement.).
The simplest way to deal with the above situation is to make the negative speed positive and increase the yaw by 180 degrees.

**Comment by flora077** [comment]
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/cc63ec4d-ab46-43eb-b22f-f0b357ba433d)
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/af47aaeb-a07f-44c0-808f-c49d4fc9190e)
The incorrect direction of speed is not related to the method of drawing the arrow. The error already exists in the tracking results obtained. As seen in the images, the first image shows the detection results, and the second image shows the tracking results. Just like the pink boxes in the previous three images, the speed is completely misestimated, but the object can still be tracked correctly

**Comment by flora077** [comment]
The reversal in the speed direction occurs in the second frame after the bbox is detected; the first frame's speed estimation is correct

**Comment by flora077** [comment]
Additionally, in the detection results, both the rotation and speed are in the right-hand lidar coordinate system. After my inspection, the detection results should be correct, with the direction of speed consistent with the direction of the vehicle's front

**Comment by flora077** [comment]
I believe I've identified the error. Upon observation, it seems that the velocity direction is only reversed when the target vehicle is facing opposite to our vehicle. This suggests that the velocity's coordinate system is based on the target vehicle, not our own. When I transformed the velocity coordinates for visualization, I converted them to our vehicle's coordinate system, leading to this discrepancy. In the detection results, the velocity is defined in the coordinate system of our vehicle (forward, left, up). However, now there's a question: How is the ego vehicle's velocity handled in the code? Or is it not considered at all?

**Comment by lixiaoyu2000** [comment]
All states in the kalman filter are described in the right-hand global frame. To model the non-linear characteristics of objects, no ego states (ego center, ego yaw, ego velocity, etc.) is fed into the tracker as the control input. However, ego states is necessary in some cases.

- In nuScenes, the detector directly outputs object observations in the global frame, so no operations are required on the tracker-end.
- In the road test, we usually observe objects in the ego frame. To adapt to Poly-MOT, a transformation from ego to global coordinate system is necessary. This transformation requires ego status to complete the conversion. The processed observations are then sent into tracker.

**Comment by flora077** [comment]
okay，i think i have understand what u say. thank u very much
