### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by 1234dgfg** [lixiaoyu2000/Poly-MOT#20]
Hello, author. Thank you very much for your outstanding contribution. I have a question and I hope to get your reply. Does the code handle the ego vehicle's velocity? If not, when the ego vehicle is moving and the vehicles on either side are stationary, how does it ensure that IDS (incorrect detection of stationary vehicles as moving) does not occur.

**Comment by lixiaoyu2000** [comment]
All the states in the tracker are described in the global frame, which decouple our tracker with ego states. However, ego states are still necessary in some cases, please refer to #18.
