### ISSUE TITLE
Jacobian wrt sigma in Bicycle model

### ISSUE THREAD

**Issue by bereze** [lixiaoyu2000/Poly-MOT#21]
Hi, I'm curious about computation of F and H matrix in the Bicycle model. From the code, the derivatives of sigma in the F and H matrix are both zeros, which means the sigma will always be 0?

**Comment by lixiaoyu2000** [comment]
Hi, according to the Jacobian matrix ([sigma line](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L914)) and [state transition function](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L972), sigma is considered to be state-invariant between two frames. Note that this does not mean “the sigma will always be 0”.

**Comment by bereze** [comment]
> Hi, according to the Jacobian matrix ([sigma line](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L914)) and [state transition function](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L972), sigma is considered to be state-invariant between two frames. Note that this does not mean “the sigma will always be 0”.
Thanks for the reply. But when I ran the test.py and added print in `stateTransition` to print `sigma` and `beta`, the two values are both 0, which confused me. In the other hand, in the state transition and measure, the jacobian of next state and measure vector 
wrt sigma seems to be simplified? Because I don't see the derivatives wrt beta, which is derived from sigma and length.

**Comment by bereze** [comment]
Thanks for the reply. But when I ran the test.py and added print in stateTransition to print sigma and beta, the two values are both 0, which confused me. In the other hand, in the state transition and measure, the jacobian of next state and measure vector
wrt sigma seems to be simplified? Because I don't see the derivatives wrt beta, which is derived from sigma and length.

**Comment by lixiaoyu2000** [comment]
Your findings are correct. To simplify calculations, beta is considered a independent state in Jacobian matrix derivation, see [jupyter](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/script/BIC_kinect_jacobian.ipynb). In addition, the situation where sigma is equal to 0 is caused by ground truth's tendency to move in a straight line in the nuscenes on the one hand and simplified calculations on the other hand.

**Comment by bereze** [comment]
So I'm wondering that when the object is turning, can this simplified model correctly estimate the sigma? The original F and H matrix seems to be extremely complicated.

**Comment by lixiaoyu2000** [comment]
Firstly, bicycle-like category has excellent tracking accuracy in the Poly-MOT. Second, judging from the results, the sigma should be correctly estimated considering that the core state displacements are well estimated from the filter.

**Comment by bereze** [comment]
Thanks for your patience, and I really appreciate it! I will do more test.

**Comment by lixiaoyu2000** [comment]
Nice! This issue will be temporarily closed.
