### ISSUE TITLE
Visualization in Camera Perspective

### ISSUE THREAD

**Issue by leeminyoung96** [lixiaoyu2000/Poly-MOT#23]
Dear authors,

Thank you for sharing such a good work!

I am new to tracking project and I would like to ask how do you obtain the tracking visualization in camera perspective.

<img width="769" alt="스크린샷 2024-02-29 오후 7 25 39" src="https://github.com/lixiaoyu2000/Poly-MOT/assets/44162173/0e949389-24a9-4b3a-b516-0eb6456ea84f">

Thank you.

**Comment by lixiaoyu2000** [comment]
Please ref to issue #5  to visualize the trajectory in the camera.

**Comment by leeminyoung96** [comment]
Dear @lixiaoyu2000 ,
Thank you for the prompt reply :)
