### ISSUE TITLE
nusc_first_token.json of trainval

### ISSUE THREAD

**Issue by Ethanol-Y** [lixiaoyu2000/Poly-MOT#24]
I recently came across the test/nusc_first_token.json files in your repository and also noticed the val/nusc_first_token.json file in the Google Drive link you shared. I'm grateful for the availability of these files, but I was wondering if it would be possible for you to provide the trainval/nusc_first_token.json file as well. Thank you very much!

**Comment by lixiaoyu2000** [comment]
Hi, `nusc_first_token.json` is actually the first frame id (`token` on nuScenes) of each seq. You only need to modify this [script](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/data/script/first_frame.py) slightly to get the first token on the train set.

**Comment by Ethanol-Y** [comment]
Thanks for your prompt reply! I'll try it.
