### ISSUE TITLE
Question about previous active trajectory

### ISSUE THREAD

**Issue by proggheli** [lixiaoyu2000/Poly-MOT#25]
Hi!
Thanks for the good work. I was wondering about the previous active trajectory T_t−1. Does this vector information come from the bounding box information from NuScenes dataset or from the bounding box information from the detection framework i.e CenterPoint? And how is the velocity calculated?

**Comment by lixiaoyu2000** [comment]
Hi, 
- The previous active trajectory $T_{t−1}$ is the attributes within the `Tracker` [class ](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/tracking/nusc_tracker.py#L33). `self.active_tras` keeps the $T_{t−1}$, which are instantiations of the `Trajectory` [class](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/tracking/nusc_trajectory.py).
- The observations (detections) vectors are from the detectors (CenterPoint, LargeKernel, etc.).
- Velocity info is provided by the detector. You can drop the velocity also, ref to #8.

**Comment by proggheli** [comment]
Thanks for the fast response!
To clearify does the data from these vector below come from the detectors (CenterPoint, LargeKernel, etc.) or directly from Nuscenes dataset?
T (CTRA) = [x, y, z, v, a, θ, ω, w, l, h]
T (BIC) = [x′, y′, z, v, a, θ, δ, w, l, h]

**Comment by lixiaoyu2000** [comment]
Neither, they are inline variables estimated by the filter.

**Comment by proggheli** [comment]
Given this information, I interpret that the vector information
Tt−1 representing the previous active trajectory that is derived from the bounding box information obtained from detectors like CenterPoint and that 
T (CTRA) = [x, y, z, v, a, θ, ω, w, l, h]
T (BIC) = [x′, y′, z, v, a, θ, δ, w, l, h]
are the estimated vectors from the filter with input Tt−1, is that correct?

**Comment by lixiaoyu2000** [comment]
The trajectory of each frame is derived by filtering the past state and the current observation (CenterPoint, etc.).
For example, for $T_{t-1}$, they are obtained by data fusion of $T_{t-2}$ and $D_{t-1}$ (the bounding box information obtained from detectors).
You can view the code to understand how Poly-MOT performs iterative inferencing.

**Comment by proggheli** [comment]
Thank you so much!!
