### ISSUE TITLE
数据集一定要使用完整的数据集是吗

### ISSUE THREAD

**Issue by snore23** [lixiaoyu2000/Poly-MOT#27]
我用nuScenes mini数据集的时候会提示KeyError: 'fd8420396768425eabec9bdddf7e64b6'，这是因为代码是使用在完整的数据集上的吗

**Comment by lixiaoyu2000** [comment]
No, Poly-MOT does not rely on inputs other than the detector. However, to determine different scenes to initialize the tracker, we set `nusc_first_token.json` in advance to save the first frame token of each scene, ref to [this](https://github.com/lixiaoyu2000/Poly-MOT?tab=readme-ov-file#prepare-the-token-table-for-online-inference). For reference, your error maybe comes from an inconsistency between the detector and `nusc_first_token.json`.

**Comment by snore23** [comment]
0%|          | 0/6019 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\柯晗\Desktop\跟踪\2024_03_22_config\data\script\first_frame.py", line 67, in <module>
    dataset_version='mini'
  File "C:\Users\柯晗\Desktop\跟踪\2024_03_22_config\data\script\first_frame.py", line 45, in extract_first_token
    if nusc.get('sample', sample_token)['prev'] == '':
  File "D:\Anaconda\app\envs\polymot\lib\site-packages\nuscenes\nuscenes.py", line 171, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
  File "D:\Anaconda\app\envs\polymot\lib\site-packages\nuscenes\nuscenes.py", line 180, in getind
    return self._token2ind[table_name][token]
KeyError: 'fd8420396768425eabec9bdddf7e64b6'

Well,the error just like this.Do I need to modify the contents of the nusc_first_token.json file?

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.

**Comment by Harden13000** [comment]
> 我用nuScenes mini数据集的时候会提示KeyError: 'fd8420396768425eabec9bdddf7e64b6'，这是因为代码是使用在完整的数据集上的吗

您好，想问下你最后跑出mini数据集的检测结果吗（json)方便加您联系方式聊一下吗

**Comment by Harden13000** [comment]
> 我用nuScenes mini数据集的时候会提示KeyError: 'fd8420396768425eabec9bdddf7e64b6'，这是因为代码是使用在完整的数据集上的吗

KeyError: 'fd8420396768425eabec9bdddf7e64b6'之前跟你一样的问题朋友

**Comment by snore23** [comment]
我最后也没跑出来mini数据集上的检测结果，你可以试试改用Trainval

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
