### ISSUE TITLE
Questions on tracking parameters

### ISSUE THREAD

**Issue by ShXiuWei1025** [lixiaoyu2000/Poly-MOT#28]
Hello, xiaoyu

I want to ask what are the initial values (means) and variances of the accelerations for different types of targets? Because the measurements doesn't contain the estimation for accelerations. Do they all begin from 0 or a specific value?

**Comment by lixiaoyu2000** [comment]
Hi, the values of accelerations are initialized to 0 in any motion model, ref to [this](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L367). Besides, their covariance is given a hand-crafted and large value (the design lies in the mathematical definition of covariance in the Kalman Filter) to model the unreliability of the initialization accelerations, ref to [this](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/motion_model.py#L389).

**Comment by ShXiuWei1025** [comment]
Thanks for your answer!
