### ISSUE TITLE
How should I check the accuracy score of the model locally

### ISSUE THREAD

**Issue by snore23** [lixiaoyu2000/Poly-MOT#29]
Dear xiaoyu,
I now have a results.json file, but I don’t seem to see a score for the overall accuracy of the model in it. How can I check the accuracy score of the model locally without having to upload the file to the competition website for evaluation?

Looking forward to your reply.

**Comment by snore23** [comment]
Well,I see.I commented out the line metrics_summary = nusc_eval.main() in test.py, so there are no results. But I found that when I didn’t comment it out, test.py would throw an error 
assert unachieved_thresholds + duplicate_thresholds + len(thresh_metrics) == self.num_thresholds 
AssertionError. 
How can I fix it?

**Comment by lixiaoyu2000** [comment]
This seems to be an error from the evaluator, not Poly-MOT. You should check the error file for tips.

**Comment by snore23** [comment]
The version of nuscenes-devkit I downloaded is 1.0.5, could it be because the version is too old?

**Comment by lixiaoyu2000** [comment]
As far as we know, Poly-MOT performs well in version 1.1.10 of nuscenes-devkit. Sorry that we have not tested how Poly-MOT works in other versions.

**Comment by snore23** [comment]
I understand now, I will download version 1.1.10. Thank you for your reply.

**Comment by lixiaoyu2000** [comment]
Nice, this issue will be temporarily closed.
