### ISSUE TITLE
Different Object detection frameworks

### ISSUE THREAD

**Issue by proggheli** [lixiaoyu2000/Poly-MOT#32]
Hi again!

I want to test the validation dataset on various object detection frameworks. So far, I've only managed to do it with CenterPoint because it's the only one I could find with pre-trained detection models in JSON format. The other frameworks seem to have models stored as .pth files. How did you run the validation dataset with LargeKernel3D-L or other detection frameworks?

**Comment by lixiaoyu2000** [comment]
Hi, please refer to issue #1.

**Comment by proggheli** [comment]
How do I regenerated LargeKernel result as you mentioned here, does it require me to retrain it? If that is the case I do not have enough GPU. https://github.com/lixiaoyu2000/Poly-MOT/issues/1#issuecomment-1727018893

**Comment by lixiaoyu2000** [comment]
Unfortunately, we don't have the bandwidth here to reproduce it, you'll need to generate detections via weight files. You can also ask the official repo to get the .json file.

**Comment by proggheli** [comment]
Okay thank you!
