### ISSUE TITLE
Plot of results

### ISSUE THREAD

**Issue by KevinCodeGitHub** [lixiaoyu2000/Poly-MOT#33]
I'm currently working on visualizing the outcomes of my project using the Poly-MOT framework. While reviewing your paper on the framework, I came across the trajectory estimation plot, which I found incredibly helpful for analyzing results across various motion models.

Would it be possible for you to share the code for generating this figure or offer any guidance on how to create it?

Thank you for your assistance, and great work on the framework!

I'm refering to this figure:
![Screenshot from 2024-05-03 14-20-29](https://github.com/lixiaoyu2000/Poly-MOT/assets/156674282/a3ff5a98-5b3f-4474-a17e-7e715efbc36d)

**Comment by lixiaoyu2000** [comment]
Hi, the plot script in your mentioned figure is [this](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/utils/Visualization.ipynb). Please refer to other viz tools in this [issue](https://github.com/lixiaoyu2000/Poly-MOT/issues/5).

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.

**Comment by proggheli** [comment]
Do you have the code on how to render this gif that you have provided in the README? 
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/117464084/3cd1f219-ac66-4244-ab0f-c6dd7f7641b5)
