### ISSUE TITLE
An error occurred with nuscene devkit during evaluation

### ISSUE THREAD

**Issue by 124451** [lixiaoyu2000/Poly-MOT#34]
nuscene-devkit version: commit 4df2701feb3436ae49edaf70128488865a3f6ff9
nuscene is the latest version at my current time。
error:can only concatenate tuple (not "int") to tuple
![nusc](https://github.com/lixiaoyu2000/Poly-MOT/assets/19453344/5c899c2c-2eb4-40a5-ac2b-3bcb919459ff)

**Comment by lixiaoyu2000** [comment]
Hi, please try the version 1.1.10 of nuscenes-devkit. Sorry that we have not tested how Poly-MOT works in other versions.

**Comment by 124451** [comment]
Oh, I got it. Thanks, that's very helpful.
