### ISSUE TITLE
可视化代码运行！

### ISSUE THREAD

**Issue by zkp0113** [lixiaoyu2000/Poly-MOT#36]
同学你好，想跟你咨询一下关于论文中可视化代码的运行。
我这边运行过程中提示
 from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/home/***/Desktop/Poly-MOT/utils/math.py)

这个错误，这个math和python自带的math 有冲突吧。

如果可以的话能否跟我取得联系，谢谢。

**Comment by lixiaoyu2000** [comment]
Hi, you can rename the `utils/math.py` file and modify the import name in Poly-MOT accordingly.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
