### ISSUE TITLE
关于测试集上的2d检测器

### ISSUE THREAD

**Issue by mengting2023** [lixiaoyu2000/Poly-MOT#37]
您好！请问在nuscenes测试集上，您使用的2d检测器是什么呢？

**Comment by lixiaoyu2000** [comment]
Hi, our method does not use any 2D detector.

**Comment by mengting2023** [comment]
您好！我看到论文中测试集的结果，输入是2D+3D
![cd205a90ea04d426070553c3df6dc795](https://github.com/user-attachments/assets/2319d633-087a-4158-9944-f6c08ba9738c)

**Comment by lixiaoyu2000** [comment]
Hi, Poly-MOT rely entirely on the detector input. Therefore, the input data of Poly-MOT actually refers to the modal of LargeKernel3D. You are welcome to view the code for a deeper understanding.

**Comment by mengting2023** [comment]
非常感谢您的耐心解答！

**Comment by lixiaoyu2000** [comment]
Nice, this issue will be temporarily closed.
