### ISSUE TITLE
Plan for inference code

### ISSUE THREAD

**Issue by MattLiutt** [lixiaoyu2000/Poly-MOT#38]
Thanks for the great work! As I went through the repo, it seems like I could not find inference code for own video for testing. Could you briefly tell me how I can inference own video using your code?

**Comment by lixiaoyu2000** [comment]
Hi, in brief, you need to prepare the following things:
- 3D Detector (Raw input): Any 3D detector results that follows the right-hand global frame, and these results must be sorted chronologically.
- First frame token (Re-init tracker): Used to identify the first frame of each sequence in your dataset. 
- Data format wrap (Valid input): Wrap your data format to match the nuScenes format.
- Yaml file change (Custom tracker): Modify configuration files to customize the tracker (time_interval, with_velo, etc.).

**Comment by MattLiutt** [comment]
Got it, I'll have a try on it
