### ISSUE TITLE
How can I combining POLY-MOT with other detectors？如何把其他检测器得到的结果用在POLY-MOT中进行跟踪任务

### ISSUE THREAD

**Issue by dszpr** [lixiaoyu2000/Poly-MOT#4]
Hi, I would like to employ result.json file from other detectors (such as StreamPETR and other detectors for nuScenes) on POLY-MOT to obtain the tracking metrics, but I don't know how to do that. Could you please help me with this issue?
Looking forward to your reply and Many thanks!!!

**Comment by lixiaoyu2000** [comment]
Hi, all you need to do is reorganize the detectors in chronological order with `reorder_detection.py`, `Required Data` section in README.md shows how to do this in detail.

**Comment by dszpr** [comment]
Thanks very much, it works well!!!
