### ISSUE TITLE
Multi-frame target visualization against single-frame background.

### ISSUE THREAD

**Issue by zkp0113** [lixiaoyu2000/Poly-MOT#40]
Hello, Doc Li；
There are only two Box objects are posted in Visualization.ipynb, When verifying my results, I want a visual output along your lines. Input the Token of a certain frame as the background (A), and put the trajectory of the detected object in the subsequent frames (A+1, A+2, A+3, A+4) into the A-frame for visual output ( Something like the first picture). However, I would like to do a multi-frame visual output based on your code like the pic shown as 2nd,

![图片2](https://github.com/user-attachments/assets/18d24976-04cc-46a5-b12e-35e195863bc6)
![图片1](https://github.com/user-attachments/assets/2c6d6048-e1bc-439b-841b-4b571c3b027a)

I want to ask you about this issue, how to convert the coordinate system of the detection object in subsequent frames to the A-frame.

Tears of gratitude.

**Comment by lixiaoyu2000** [comment]
@liudedong1130 Could you provide some advice?

**Comment by liudedong1130** [comment]
Hello
You can meet your needs using the `Visualization.ipynb` file. You only need to modify the `in[2]` cell in the `Visualization.ipynb` file. 
1. Manually add the box information you want to visualize into list `box_list`, just like how two boxes are added in the file. The boxes should use global coordinate. 
2. Specify the `sample_token` for the background frame. Then, the `coordinate_conversion` function will transform all box's coordinate in `box_list` into the background frame's coordinate based on the `sample_token`.
3. Execute the `Visualization.ipynb` file to complete the visualization.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
