### ISSUE TITLE
如何得到可视化视频或动图？

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#5]
您好，非常感谢您的项目，并且恭喜您在nuscenes上取得了令人赞叹的成绩。我想知道我该如何得到跟踪结果的视频或者动图，就像您首页放的动图一样，我在运行python test.py后仅得到了.json文件，可是我想更直观的看到跟踪的成绩。所以，请问我该如何获得像您首页摘要中一样的可视化的视频

**Comment by lixiaoyu2000** [comment]
Hi, sorry for the late reply. We have open sourced the visualization part in the BEV space, see the `Visualization` in the `README.MD` or [this jupyter](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/utils/Visualization.ipynb). We don't yet have the bandwidth to reorganize the visualization code in 2D/3D space (which you need), but you can obtain the visualization effect through the following methods:

- For Poly-MOT, all you need to do is project the class [NuscBox](https://github.com/lixiaoyu2000/Poly-MOT/blob/aa8a70d83914439f5cb4e8df2a0fd901aa7a12cf/geometry/nusc_box.py#L13C7-L13C14) onto the pixel plane. For this implementation, you can refer to [Nuscenes official code](https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L98).
- Another way is to use the visualization scripts of AB3DMOT and other projects. You can refer to the [this](https://github.com/xinshuoweng/AB3DMOT/blob/61f3bd72574093e367916c757b4747ca445f978c/AB3DMOT_libs/vis.py#L10) or  #2.

BTW, is your email address `lyfzs980507@163.com`? If so, I will reply here for convenience. Hope the above can help you, if you have any further questions, please contact me.

**Comment by flora077** [comment]
Yes, this is my mailbox, thank you very much for your reply。
 I will try to get this part done,
thank you again for replying to me!

**Comment by lixiaoyu2000** [comment]
Great! This issue will be temporarily closed.

**Comment by Harden13000** [comment]
> Yes, this is my mailbox, thank you very much for your reply。 I will try to get this part done, thank you again for replying to me!

您好，请问您做出可视化结果了吗，可以参考下代码吗

**Comment by flora077** [comment]
> > Yes, this is my mailbox, thank you very much for your reply。 I will try to get this part done, thank you again for replying to me!
> 
> 您好，请问您做出可视化结果了吗，可以参考下代码吗

是的，我已经做出了可视化结果，其中右侧为跟踪BEV视角下结果，每一个id对应一个颜色
![image](https://github.com/lixiaoyu2000/Poly-MOT/assets/94901804/8e84a284-1dba-4922-80d2-b72bb179ad81)

**Comment by Harden13000** [comment]
您好，可以提供下代码思路吗想学习一下，谢谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月02日 15:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lixiaoyu2000/Poly-MOT] 如何得到可视化视频或动图？ (Issue #5) |

Yes, this is my mailbox, thank you very much for your reply。 I will try to get this part done, thank you again for replying to me!

您好，请问您做出可视化结果了吗，可以参考下代码吗

是的，我已经做出了可视化结果，其中右侧为跟踪BEV视角下结果，每一个id对应一个颜色
image.png (view on web)

**Comment by flora077** [comment]
加我vx吧 19821735258

**Comment by lixiaoyu2000** [comment]
> > > Yes, this is my mailbox, thank you very much for your reply。 I will try to get this part done, thank you again for replying to me!
> > 
> > 
> > 您好，请问您做出可视化结果了吗，可以参考下代码吗
> 
> 是的，我已经做出了可视化结果，其中右侧为跟踪BEV视角下结果，每一个id对应一个颜色 ![image](https://private-user-images.githubusercontent.com/94901804/318691411-8e84a284-1dba-4922-80d2-b72bb179ad81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDUzODIsIm5iZiI6MTcxMjA0NTA4MiwicGF0aCI6Ii85NDkwMTgwNC8zMTg2OTE0MTEtOGU4NGEyODQtMWRiYS00OTIyLTgwZDItYjcyYmIxNzlhZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTIxNTJlZTg3NjYzMzkzNjNmZThmZWFhYWNmYjNmZjc1ZmE1MGQ3ZGU5MDJkNGM3ZjRhZTY2ZDcyNTZhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xNNlQGTDHxtNUoX2jcyVcdUOgjwJtI5YUBMhrijhzDs)


Very nice visualization! It would be very helpful for the community if you could share (maybe a PR :grin:) this script :blush:.

**Comment by Harden13000** [comment]
您好，搜索账号显示不存在，方便加下我的吗，zyzs_lzysh06



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月02日 16:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lixiaoyu2000/Poly-MOT] 如何得到可视化视频或动图？ (Issue #5) |

加我vx吧 19821735258

**Comment by flora077** [comment]
OK

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月02日 16:07 |
| 收件人 | lixiaoyu2000/Poly-MOT ***@***.***> |
| 抄送人 | flora077 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [lixiaoyu2000/Poly-MOT] 如何得到可视化视频或动图？ (Issue #5) |

您好，搜索账号显示不存在，方便加下我的吗，zyzs_lzysh06



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月02日 16:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lixiaoyu2000/Poly-MOT] 如何得到可视化视频或动图？ (Issue #5) |

加我vx吧 19821735258
