### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#6]
Hello, if I want to use my own dataset to evaluate the algorithm, what should I do? That is, now I have the result result.json of the target tracking, and I also have the truth val.json, is there any mature code that can refer to it?

**Comment by lixiaoyu2000** [comment]
Hi, there are two insights you can refer to:
- Inference: If you want to employ Poly-MOT on your custom dataset, all need to do is reimplentent [NuScenesloader](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/dataloader/nusc_loader.py).
- Evaluate: After obtaining tracking results on your custom dataset, it is obvious that the evaluation script of [nuScenes ](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/test.py#L93) is not suitable for you. However, I think [motmetric ](https://github.com/cheind/py-motmetrics) maybe a potentially viable method of adaptive evaluation for you.

**Comment by flora077** [comment]
Yes, I've successfully run poly-mot with my own dataset and the results are very good after visualization, but I'm having trouble with the evaluation, you said that motmetric only works with 2D mot, which is frustrating, I'm trying to change motmetric to work with 3D mot. Why is there no ready-made evaluation algorithm for 3D MOT, alas!

**Comment by lixiaoyu2000** [comment]
Hi, perhaps you could refer to [AB3DMOT ](https://github.com/xinshuoweng/AB3DMOT/tree/master/scripts)to evaluate the tracking result on the custom dataset, since they provide two `AMOTA` implentent on both KITTI and nuScenes?
BTW, maybe good visualization results are convincing enough in engineering implementation? :joy:

**Comment by flora077** [comment]
Okay, I'll take a closer look and thank you for your prompt reply🤭

**Comment by lixiaoyu2000** [comment]
Issue closed.
