### ISSUE TITLE
Real-time

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#7]
Hi, I saw that the processing speed is 3 frames per second in your paper HighLights, but for a two-stage tracking algorithm, this is not a very fast speed, what causes the algorithm to not be very real-time?😄😄

**Comment by lixiaoyu2000** [comment]
In fact, we outperform most methods with similar accuracy (simpletrack, Immortal_tracker, etc.). The core reason is the `GIoU` calculation (Although we proposed the [half-parallel GIOU operator](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/geometry/nusc_distance.py#L150) under the Python implementation, x3 fast than serial). You can use C++ implementation or other similarity metric for faster inference speed.
